<?php 
    $value_id = (new Attendance_Model_Attendance())->getCurrentValueId();
    $receiver_id = 0;
   
    if(!empty($value_id)) {
          $messageModel = new Attendance_Model_Message();
          $messages = array_values($messageModel->adminInbox($value_id));
          $customer = $this->getCustomer();
          $sender_id = $this->getSenderId();
      ?>
 
<div class="row">
    <div class="col-md-12">
        <div class="page-content-wrapper form-horizontal">
            <div class="content solo-page">
                <h3 class="title-editor border-blue text-center">
                    <?php echo p__("attendance", "Messages"); ?>
                 <a href="/attendance/application/users"
                    class="color-blue btn sb-tour pull-right" style="margin-right:16px;">
                    <?php echo  p__("attendance", "New Customer"); ?>
                  </a>
                </h3>

                <div class="subcontent content-color container-fluid">
                    <div class="form-group">
                       <div class="col-md-12">
                          <?php if(!empty($messages) || $sender_id > 0) : ?>
                            <div class="messaging">
                                  <div class="inbox_msg">
                                    <div class="inbox_people">
                                      <div class="headind_srch">
                                        <div class="recent_heading">
                                          <h4> <?php echo p__("attendance", "Recent"); ?></h4>
                                        </div>
                                     </div>
                                      <div class="inbox_chat">
                                     <?php foreach($messages as $key => $value): ?>
                                        <div class="chat_list <?php echo $sender_id == $value['sender_id'] ? 'active_chat' : ''; ?>"> 
                                         <a href="/attendance/application/messages/sender_id/<?php echo $value['sender_id']; ?>"> 
                                          <div class="chat_people">
                                            <?php if($value['sender_image']!='') : ?>
                                            <div class="chat_img"> 
                                                <img src="/images/customer/<?php echo $value['sender_image']; ?>" alt=""> 
                                            <?php else: ?>
                                              <div class="chat_img"> 
                                                <img src="/app/local/modules/Attendance/features/attendance/assets/media/customer-placeholder.png" alt=""> 
                                            <?php endif;?>
                                            </div>
                                             <div class="chat_ib">
                                              <h5><?php echo $value['sender_first_name'].' '.$value['sender_last_name']; ?> <span class="chat_date"><?php echo  date("d-M-Y g:i a", strtotime($value['created_at'])); ?></span></h5>
                                            </div>
                                          </div>
                                        </a>
                                        </div>  
                                    <?php endforeach; ?>
                                      </div>
                                    </div>
                                    <div class="mesgs">
                                      <div class="msg_title">
                                        <?php if(!empty($customer)): ?>
                                          <h4><?php echo $customer->getFirstname(); ?> <?php echo $customer->getLastname(); ?></h4>
                                        <?php endif; ?>
                                      </div>
                                      <div class="msg_history">
                                    <?php foreach($this->getListingMessages() as $key => $value): 
                                        $receiver_id = $value['sender_id'];
                                      ?>

                                     <?php if($value['receiver_id'] == 0) : ?>
                                        <div class="incoming_msg">
                                          <div class="received_msg">
                                            <div class="received_withd_msg">
                                              <p> <?php echo $value['message']; ?> </p>
                                              <span class="time_date"> 
                                                <?php echo  date("g:i a", strtotime($value['created_at'])); ?>   |    <?php echo  date("d-M", strtotime($value['created_at'])); ?></span></div>
                                          </div>
                                        </div>
                                    <?php else: ?>
                                        <div class="outgoing_msg">
                                          <div class="sent_msg">
                                            <p><?php echo $value['message']; ?></p>
                                            <span class="time_date"> 
                                                <?php echo  date("g:i a", strtotime($value['created_at'])); ?>   |    <?php echo  date("d-M", strtotime($value['created_at'])); ?></span> </div>
                                        </div>
                                    <?php endif;?>

                                    <?php endforeach; ?>
                                      </div>
                                      <form  action="<?php echo $this->getUrl('attendance/application/savemessage'); ?>" method="post" id="messageForm">
                                      <div class="type_msg">
                                        <div class="input_msg_write">
                                             <input type="hidden" name="value_id" value="<?php echo $value_id; ?>">
                                              <input type="hidden" name="receiver_id" value="<?php echo $this->getSenderId(); ?>">
                                          <input type="text" class="write_msg" name="message" placeholder="<?php echo p__("attendance", "Type a message"); ?>" />
                                          <button class="msg_send_btn" type="submit"><i class="fa fa-paper-plane-o" aria-hidden="true"></i></button>
                                        </div>
                                      </div>
                                     </form>
                                    </div>
                                  </div>
                                </div>
                              <?php else: ?>
                                <p class="text-center">
                                   <?php echo p__("attendance", "No Messages yet!"); ?>
                                </p>
                              <?php endif ?>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>


<?php } else{ ?>

<div class="row">
    <div class="col-md-12">
        <div class="page-content-wrapper form-horizontal">
            <div class="content solo-page">
                <div class="subcontent content-color container-fluid">
                    <div class="container ">
                        <div class="row text-center">
                            <div class="alert alert-info"><h5><?php echo p__("attendance", "This features is not activated for this application, For activate the features go to : "); ?> <a href="/application/customization_features/list"><b> Editor > features</b> </a></h5></div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<?php }?>

<style type="text/css">
img{ max-width:100%;}
.inbox_people {
  background: #f8f8f8 none repeat scroll 0 0;
  float: left;
  overflow: hidden;
  width: 40%; border-right:1px solid #c4c4c4;
}
.inbox_msg {
  border: 1px solid #c4c4c4;
  clear: both;
  overflow: hidden;
}
.top_spac{ margin: 20px 0 0;}
.recent_heading {float: left; width:40%;}
.headind_srch{ padding:10px 29px 10px 20px; overflow:hidden; border-bottom:1px solid #c4c4c4;}

.recent_heading h4 {
  color: #05728f;
  font-size: 21px;
  margin: auto;
}
.chat_ib h5{ font-size:15px; color:#464646; margin:0 0 8px 0;}
.chat_ib h5 span{ font-size:13px; float:right;}
.chat_ib p{ font-size:14px; color:#989898; margin:auto}
.chat_img {
  float: left;
  width: 11%;
}
.chat_ib {
  float: left;
  padding: 0 0 0 15px;
  width: 88%;
}
.chat_people{ overflow:hidden; clear:both;}
.chat_list {
  border-bottom: 1px solid #c4c4c4;
  margin: 0;
  padding: 18px 16px 10px;
}
.inbox_chat { height: 550px; overflow-y: scroll;}
.active_chat{ background:#ebebeb;}
.incoming_msg_img {
  display: inline-block;
  width: 6%;
}
.received_msg {
  display: inline-block;
  padding: 0 0 0 10px;
  vertical-align: top;
  width: 92%;
 }
 .received_withd_msg p {
  background: #ebebeb none repeat scroll 0 0;
  border-radius: 3px;
  color: #646464;
  font-size: 14px;
  margin: 0;
  padding: 5px 10px 5px 12px;
  width: 100%;
}
.time_date {
  color: #747474;
  display: block;
  font-size: 12px;
  margin: 8px 0 0;
}
.received_withd_msg { width: 57%;}
.mesgs {
  float: left;
  padding: 0px 15px 0 25px;
  width: 60%;
  background-color: #fff;
}
 .sent_msg p {
  background: #05728f none repeat scroll 0 0;
  border-radius: 3px;
  font-size: 14px;
  margin: 0; color:#fff;
  padding: 5px 10px 5px 12px;
  width:100%;
}
.outgoing_msg{ overflow:hidden; margin:26px 0 26px;}
.sent_msg {
  float: right;
  width: 46%;
}
.input_msg_write input {
  background: rgba(0, 0, 0, 0) none repeat scroll 0 0;
  border: medium none;
  color: #4c4c4c;
  font-size: 15px;
  min-height: 48px;
  width: 100%;
}

.type_msg {border-top: 1px solid #c4c4c4;position: relative;}
.msg_send_btn {
  background: #05728f none repeat scroll 0 0;
  border: medium none;
  border-radius: 50%;
  color: #fff;
  cursor: pointer;
  font-size: 17px;
  height: 33px;
  position: absolute;
  right: 0;
  top: 11px;
  width: 33px;
}
.messaging { padding: 0 0 50px 0;}
.msg_history {
  height: 516px;
  overflow-y: auto;
  margin-top: 40px;
}
.msg_title{
  border-bottom: 1px solid #05728f;
  color: #05728f;
  font-size: 21px;
}

</style>
<script type="text/javascript">
    $(".msg_history").animate({ scrollTop: $('.msg_history').prop("scrollHeight")}, 1000);

     $('#messageForm').submit(function(e) {
          e.preventDefault();
          var formData = new FormData(this);    
        if($(this).valid()) {
            reload(this, this.action, formData, function(data) {  
                if(data.success) {
                    location.reload();
                }
            });
        }
        return false;
    });   

 
</script>
 