 <div class="row">
    <div class="col-md-12">
        <div class="page-content-wrapper form-horizontal">
            <div class="content solo-page">
                <h3 class="title-editor border-blue text-center">
                    <?php echo  p__("attendance", "Users"); ?>

                  <a href="/attendance/application/messages"
                    class="color-blue btn sb-tour pull-right" style="margin-right:16px;">
                    <?php echo  p__("attendance", "Back to Messages"); ?>
                  </a>

                </h3>
               
                  <div class="subcontent content-color container-fluid">
                    <div class="form-group">
                     <div class="col-md-12">
                           <table id="dynamic-customers"
                                   class="table content-white-bkg sb-pager">
                                <thead>
                                    <tr class="border-grey">
                                        <th data-dynatable-column="customer_id"
                                            style="width: 10%;"><?php echo  p__("attendance", "ID"); ?></th>
                                        <th data-dynatable-column="email"
                                            style="width: 25%;"><?php echo  p__("attendance", "Email"); ?></th>
                                        <th data-dynatable-column="firstname"
                                            style="width: 25%;"><?php echo  p__("attendance", "User"); ?></th>
                                        <th data-dynatable-column="created_at"
                                            style="width: 20%;"><?php echo  p__("attendance", "Date"); ?></th>
                                        <th style="width: 20%;"
                                            class="text-right"><?php echo p__("attendance","Messages"); ?></th>
                                    </tr>
                                </thead>
                                <tbody></tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<link href="/app/sae/design/desktop/flat/js/dynatable/jquery.dynatable.css"
      media="screen"
      rel="stylesheet"
      type="text/css">
<script type="text/javascript"
        src="/app/sae/design/desktop/flat/js/dynatable/jquery.dynatable.js"></script>

<style type="text/css">
    #dynamic-customers {
        margin-top: 15px;
    }
</style>

<script type="text/javascript">
    var uriParams = {};
    let rowTemplate = `
    <tr class="dynarow">
        <td>
            <b>#(CUSTOMER_ID)</b>
        </td>
        <td>(EMAIL)</td>
        <td>(NAME)</td>
        <td>(DATE)</td>
        <td >
             <a href="/attendance/application/messages/sender_id/(CUSTOMER_ID)"
               class="btn btn-xs btn-info message-customer pull-right">
                <?php echo __js("Messages Now") ?>
            </a>
        </td>
    </tr>`;

    function rowWriter(rowIndex, record, columns, cellWriter) {
        var ishide = record.status == "1" ? 'hide' : '';
        if(record.status == "2"){
            var ishide = record.endlatlong == "0,0" ? 'hide' : '';
        }

        return rowTemplate
            .replace(/\(CUSTOMER_ID\)/g, record.id)
            .replace(/\(EMAIL\)/g, record.email)
            .replace(/\(NAME\)/g, record.name)
            .replace(/\(DATE\)/g, record.created_at)
    }
    $.dynatableSetup({
        table: {
            defaultColumnIdStyle: 'noStyle'
        },
        features: {
            paginate: true,
            sort: true,
            pushState: true,
            search: true,
            recordCount: true,
            perPageSelect: false,
        },
    });

    let tableCustomers = $('#dynamic-customers');

    tableCustomers.bind('dynatable:preinit', function(e, dynatable) {
        dynatable.utility.textTransform.noStyle = function(text) {
            return text;
        };
    });
  
    tableCustomers.bind('dynatable:init', function(e, dynatable) {
            dynatable.queries.functions['to'] = function(r, val) {
              return queryValue;
            };  
            dynatable.queries.functions['from'] = function(r, val) {
              return queryValue;
            }; 
                    
      });

    tableCustomers.bind('dynatable:afterProcess', function (e, data) {
        uriParams = data.queries;
    });
    

    tableCustomers.bind('dynatable:push', function(e, dynatable) {
          uriParams = dynatable.queries;   
    });

    // And on the table
    tableCustomers.dynatable({
        dataset: {
            ajax: true,
            ajaxUrl: '/customer/application/fetch-customers',
            ajaxOnLoad: true,
            records: [],
            perPageDefault: 25
        },
        inputs: {
            processingText: '<?php echo __jss("Loading ...") ?>',
            searchPlaceholder: '<?php echo __jss("Search user ...") ?>',
            recordCountText: '<?php echo __jss("Showing") ?> ',
            filteredFrom: ' (<?php echo __jss("filtered from #TOTAL# total records") ?>)',
            recordText: '<?php echo __jss("record") ?>',
            recordTextPlural: '<?php echo __jss("records") ?>',
            textOf: '<?php echo __jss("of") ?>',
            textTo: '<?php echo __jss("to") ?>',
            queries: $('.dt-search')
        },
        writers: {
            _rowWriter: rowWriter
        }
    });
 
 
 </script>

<style type="text/css">
    .dynatable-record-count{
        bottom: 0px !important;
    }
</style>